CREATE TABLE BUS (
    ROUTENO VARCHAR(20) PRIMARY KEY,
    SOURCE VARCHAR(50),
    DESTINATION VARCHAR(50)
);

CREATE TABLE PASSENGER (
    PID INT PRIMARY KEY,
    PNAME VARCHAR(50),
    DOB DATE,
    GENDER CHAR(1) NOT NULL,
    CHECK (GENDER IN ('M', 'F', 'O'))
);

CREATE TABLE BOOK_TICKET (
    PID INT,
    ROUTENO VARCHAR(20),
    JOURNEY_DATE DATE,
    SEAT_NO INT,
    FOREIGN KEY (PID) REFERENCES PASSENGER(PID),
    FOREIGN KEY (ROUTENO) REFERENCES BUS(ROUTENO),
    PRIMARY KEY (PID, ROUTENO, JOURNEY_DATE)
);

INSERT INTO BUS VALUES ('R1', 'VISAKHAPATNAM', 'MUMBAI');
INSERT INTO BUS VALUES ('R2', 'VISAKHAPATNAM', 'HYDERABAD');
INSERT INTO BUS VALUES ('R3', 'VISAKHAPATNAM', 'CHENNAI');
INSERT INTO BUS VALUES ('R4', 'VISAKHAPATNAM', 'KOLKATA');
SELECT * FROM BUS;

INSERT INTO PASSENGER VALUES (1, 'ABC', '17-OCT-1992', 'F');
INSERT INTO PASSENGER VALUES (2, 'ABC', '12-SEP-1999', 'F');
INSERT INTO PASSENGER VALUES (3, 'ABC', '31-JUL-1992', 'F');
INSERT INTO PASSENGER VALUES (4, 'ABC', '16-JAN-1985', 'M');
SELECT * FROM PASSENGER;

INSERT INTO BOOK_TICKET VALUES (1, 'R3', '17-APR-2023', 6);
INSERT INTO BOOK_TICKET VALUES (2, 'R1', '03-AUG-2023', 9);
INSERT INTO BOOK_TICKET VALUES (3, 'R2', '27-MAY-2023', 7);
INSERT INTO BOOK_TICKET VALUES (4, 'R4', '24-JUL-2023', 13);
SELECT * FROM BOOK_TICKET;

SELECT P.PNAME FROM PASSENGER P, BOOK_TICKET B WHERE P.PID = B.PID AND B.ROUTENO = 'R1' AND B.JOURNEY_DATE = '21-AUG-2015';

SELECT DISTINCT P.PNAME FROM PASSENGER P, BOOK_TICKET B WHERE P.PID = B.PID;
SELECT DISTINCT P.PNAME FROM PASSENGER P JOIN BOOK_TICKET B ON P.PID = B.PID GROUP BY P.PID, P.PNAME HAVING COUNT (DISTINCT B.ROUTENO) > 1;

SELECT B.ROUTENO, COUNT(BT.ROUTENO) AS RESERVATIONS FROM BUS B LEFT JOIN BOOK_TICKET BT ON B.ROUTENO = BT.ROUTENO GROUP BY B.ROUTENO;
