create table employees (eid int primary key, ename varchar2(25), designation varchar2(20), salary int);
desc employees;
insert into employees values (1, 'ABC', 'HR', 60000);
insert into employees values (2, 'DEF', 'Manager', 50000);
insert into employees values (3, 'GHI', 'Marketing', 30000);
insert into employees values (4, 'JKL', 'IT', 70000);
insert into employees values (5, 'MNO', 'Designer', 40000);
select * from employees;
alter table employees add (eage int);
select * from employees;
update employees set eage = 25 where eid = 1;
update employees set eage = 30 where eid = 2;
update employees set eage = 22 where eid = 3;
update employees set eage = 27 where eid = 4;
update employees set eage = 24 where eid = 5;
select * from employees;
alter table employees modify eage float;
desc employees;
select * from employees;
alter table employees drop column eage;
select * from employees;
update employees set designation = 'Officer' where eid = 1;
select * from employees;
commit;
truncate table employees;
select * from employees;
rename employees to workforce;
select * from workforce;
drop table workforce;
