CREATE TABLE STUDENT (SID INT, SNAME VARCHAR2 (50), AGE INT);
INSERT INTO STUDENT (SID, SNAME, AGE) VALUES (0997, 'Aritt', 20);
INSERT INTO STUDENT VALUES (0189, 'Hemant', 19);
INSERT INTO STUDENT VALUES (1428, 'Yash', 21);
INSERT INTO STUDENT VALUES (1911, 'Kashyap', 19);
SELECT * FROM STUDENT;
COMMIT;
INSERT INTO STUDENT VALUES (69, 'Mahesh Dalle', 30);
ROLLBACK;
INSERT INTO STUDENT VALUES (88, 'Mamta MC', 40);
SAVEPOINT S1;
INSERT INTO STUDENT VALUES (100, 'Baap', 75);
ROLLBACK TO S1;

CREATE TABLE COURSE (CID INT, CNAME VARCHAR2 (20), CREDIT INT);
INSERT INTO COURSE VALUES (01, 'DBMS', 3);
INSERT INTO COURSE VALUES (02, 'AI', 3);
INSERT INTO COURSE VALUES (03, 'DAA', 3);
INSERT INTO COURSE VALUES (04, 'FLAT', 3);
SELECT * FROM COURSE;
SELECT * FROM TAB;

CREATE TABLE EMPLOYEE (EID INT, ENAME VARCHAR2 (50), DESIGNATION VARCHAR2 (20));
INSERT INTO EMPLOYEE VALUES (1, 'ABC', 'Manager');
INSERT INTO EMPLOYEE VALUES (1, 'DEF', 'Professor');
INSERT INTO EMPLOYEE VALUES (1, 'GHI', 'Doctor');
SELECT * FROM EMPLOYEE;
